version: "3"
services:
  springboot-app:
    container_name: springapi_liftnotes
    image: springboot-app
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: liftnotes_users
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306

  mysqldb:
    container_name: liftnotes_users
    image: mysql
    volumes:
      - C:\Users\dtera\Documents\Projects\SpringBoot\liftnotes_db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: workouts
      MYSQL_ROOT_PASSWORD: password
